version: "4.0"

services:
  user-service:
    build: ./demo-user-service
    image: demo/user-service
    ports:
      - "8081:8081"
    networks:
      - demo-network
    depends_on:
      - mysql

  ticket-service:
    build: ./demo-ticket-service
    image: demo/ticket-service
    ports:
      - "8082:8082"
    networks:
      - demo-network
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0.33
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d
    networks:
      - demo-network


  otel-collector:
    image: otel/opentelemetry-collector-contrib
    volumes:
      - ./otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml
    ports:
      - 1888:1888 # pprof extension
      - 8888:8888 # Prometheus metrics exposed by the Collector
      - 8889:8889 # Prometheus exporter metrics
      - 13133:13133 # health_check extension
      - 4317:4317 # OTLP gRPC receiver
      - 55679:55679 # zpages extension
    depends_on:
      - jaeger-service
    networks:
      - demo-network

  jaeger-service:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
    networks:
      - demo-network

networks:
  demo-network:
    driver: bridge
