FROM apache/skywalking-python:1.0.0-kafka-py3.11-slim

RUN apt-get update \
    && apt-get upgrade -y \
    && apt-get install -y gcc default-libmysqlclient-dev pkg-config \
    && rm -rf /var/lib/apt/lists/*

COPY . .

RUN pip install --upgrade pip \
    && pip install mysqlclient \
    && pip install flask \
    && pip install flask_sqlalchemy

ENV SW_AGENT_NAME=test-flask
ENV SW_AGENT_COLLECTOR_BACKEND_SERVICES=oap-server:11800
ENV SW_PLUGIN_SQL_PARAMETERS_MAX_LENGTH=500

CMD ["run", "-p", "flask", "--app", "app", "run", "--host=0.0.0.0"]